# Generated by Django 3.2.23 on 2023-11-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_pictures/default_profile.jpeg', upload_to='profile_pictures', verbose_name='Imagen de perfil'),
        ),
    ]
