# Generated by Django 3.2.23 on 2023-11-20 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
