# Generated by Django 3.2.23 on 2023-11-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('inventory', models.PositiveIntegerField(verbose_name='Inventario')),
                ('description', models.TextField(null=True, verbose_name='Descripción')),
                ('cover', models.ImageField(upload_to='products', verbose_name='Imagen del producto')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('product_list', models.ManyToManyField(default=None, to='admin_panel.Product')),
            ],
            options={
                'verbose_name': 'Categorías',
                'verbose_name_plural': 'Categorías',
            },
        ),
    ]
