# Generated by Django 3.2.23 on 2023-11-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='DNI'),
        ),
    ]
